app:
   image: fabuloso/apollo-spike
   ports:
      - "8080:8080"
   links:
      - mongo
      - queue
mongo:
    image: mongo

queue:
    image: rmohr/activemq:5.13.3
    ports:
      - "61616:61616"
      - "8161:8161"

view:
    image: fabuloso/view
    ports:
      - "8081:8081"
    links:
      - queue
      - mongo