app:
  image: fabuloso/apollo-spike
  ports:
    - "8080:8080"
  links:
    - mongo

dashboard:
  image: mlabouardy/hystrix-dashboard
  ports:
    - "9080:9002"
  links:
    - app

mongo:
  image: mongo